name: Node CI Workflow

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  set-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.set-branch.outputs.branch }}
    steps:
      - name: Set workflow branch
        id: set-branch
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [ "$BRANCH_NAME" == "main" ]; then
            echo "::set-output name=branch::main"
          else
            echo "::set-output name=branch::dev"
          fi

  ci-dev:
    needs: set-branch
    if: ${{ needs.set-branch.outputs.branch == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: shardeum/github-automation/.github/workflows/node-ci-shared.yml@RED-120
        with:
          node-version: '18.16.1' 
          lint-required: false
          format-check-required: false
          apply-patches-required: true
          unit-tests-required: false

  ci-main:
    needs: set-branch
    if: ${{ needs.set-branch.outputs.branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: shardeum/github-automation/.github/workflows/node-ci-shared.yml@RED-120
        with:
          node-version: '18.16.1' 
          lint-required: false
          format-check-required: false
          apply-patches-required: true
          unit-tests-required: false

